/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package portiappp;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;

/**
 *
 * @author Jorge Loredo
 */
public class Historial extends javax.swing.JFrame {
    Crepa p;
    private ArrayList<Crepa> lis;
    private ArrayList<Crepa> los;
    public Historial() {
        initComponents();
             this.setLocationRelativeTo(null);
              lis = new ArrayList <>();
              los = new ArrayList <>();
              File ruta = new File("listacrepas.txt");
        try{
            
            FileReader fi = new FileReader(ruta);
            BufferedReader bu = new BufferedReader(fi);
            
            
            String linea = null;
            while((linea = bu.readLine())!=null){
                StringTokenizer st = new StringTokenizer(linea, ",");
                p = new Crepa();
                p.setNombre(st.nextToken());
                p.setFondo(st.nextToken());
                p.setElemento1(st.nextToken());
                p.setElemento2(st.nextToken());
                p.setEnv(st.nextToken());
                lis.add(p);
            }
            bu.close();
        }catch(Exception ex){
            System.out.println("error");
        }
        verDatos();
    }
       public void verDatos(){
        String Mat[][] = new String [lis.size()][5];
        Crepa aux;
        for (int i = 0; i<lis.size(); i++){
            aux = lis.get(i);
            Mat[i][0] = aux.getNombre();
            Mat[i][1] = aux.getFondo();
            Mat[i][2] = aux.getElemento1();
            Mat[i][3] = aux.getElemento2();
            Mat[i][4] = aux.getEnv();
                    }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            Mat,
            new String [] {
                "Nombre", "Fondo", "Elemento 1", "Elemento2", "Envoltura"
            }
        ));
    }
    public void verDatos1(){
        String Mat[][] = new String [los.size()][5];
        Crepa aux;
        for (int i = 0; i<los.size(); i++){
            aux = los.get(i);
            Mat[i][0] = aux.getNombre();
            Mat[i][1] = aux.getFondo();
            Mat[i][2] = aux.getElemento1();
            Mat[i][3] = aux.getElemento2();
            Mat[i][4] = aux.getEnv();
                    }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            Mat,
            new String [] {
                "Nombre", "Fondo", "Elemento 1", "Elemento2", "Envoltura"
            }
        ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Historial de Ventas");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Fondo", "Ingrediente 1", "Ingrediente 2", "Envoltura"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 850, 390));

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "Fondo", "Ingrediente 1", "Ingrediente 2", "Envoltura" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 150, 40));

        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 530, 600, 40));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 590, 180, 50));

        jButton4.setBackground(new java.awt.Color(255, 0, 0));
        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Reestablecer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 590, 200, 50));

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Eliminar Historial");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 590, 210, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/portiappp/red-wallpaper-background.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, -1, 360));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/portiappp/red-wallpaper-background.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, -10, 440, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/portiappp/red-wallpaper-background.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/portiappp/red-wallpaper-background.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 440, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      VentanaEmpleado a = new VentanaEmpleado();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 
        int a=JOptionPane.showConfirmDialog(null,"¿Estas seguro?");  
if(a==JOptionPane.YES_OPTION){  
    lis.clear();
        verDatos();
        File ruta = new File("listacrepas.txt");
        if(ruta.delete())
        JOptionPane.showMessageDialog(null,"Historial Eliminado");
}        
       
        
      
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       int c;
       
        try{
            c = jTable1.getSelectedRow();
            lis.remove(c);
            
        }catch( Exception e){
            JOptionPane.showMessageDialog(null, "Favor de escoger una crepa");
        }try{
            
            File fi = new File("listacrepas.txt");
           PrintWriter Escribe = new PrintWriter(fi, "utf-8");
            Crepa aux;
            for(int i= 0; i<lis.size(); i++){
                aux =lis.get(i);
                aux.guardar(Escribe);
            }
            Escribe.close();
        }catch(Exception ex){
            System.out.println("error");
        }
               
               
        verDatos();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        
        int c = jComboBox1.getSelectedIndex();
        String a = jTextField1.getText();
         los = new ArrayList <>();
        if(c==0){
            for(int i = 0; i<lis.size(); i++){
                if(lis.get(i).getNombre().equals(a))
                    los.add(lis.get(i));
            }
            verDatos1();
        }
        else if(c==1){
            for(int i = 0; i<lis.size(); i++){
                if(lis.get(i).getFondo().equals(a))
                    los.add(lis.get(i));
            }
            verDatos1();
        }
        else if(c==2){
            for(int i = 0; i<lis.size(); i++){
                if(lis.get(i).getElemento1().equals(a))
                    los.add(lis.get(i));
            }
            verDatos1();
        }
        else if(c==3){
            for(int i = 0; i<lis.size(); i++){
                if(lis.get(i).getElemento2().equals(a))
                    los.add(lis.get(i));
            }
            verDatos1();
        }
        else if(c==4){
            for(int i = 0; i<lis.size(); i++){
                if(lis.get(i).getEnv().equals(a))
                    los.add(lis.get(i));
            }
            verDatos1();
        }
        else {
             for(int i = 0; i<lis.size(); i++){
                if(lis.get(i).getNombre().equals(a))
                    los.add(lis.get(i));
            }
            verDatos1();
        }
        jTextField1.setText("");
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        verDatos();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Historial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
