
package portiappp;

import java.util.*;
import java.io.*;
import java.io.FileReader;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

public class VentanaCliente extends javax.swing.JFrame {

     public String nombre;
    public     String Fondo;
    public String Elemento1;
    public String Elemento2;
    public double totalrecaudado;
    public String Lista;
    public int Envoltura;
    public int crepasrealizadas;
    public String lista;
    public String envoltura;
    public double gastos;
    public double costomasa;
    public int nutellas;
    public int cajetas;
    public int merme;
    public int platanos;
    public int fresas;
    public int lecheras;
    public int Envolturas;
    Crepa p;
    
 private ArrayList<Crepa> listalocal;
 private ArrayList<Crepa> Listapedidos;
    public VentanaCliente() {
        
         listalocal = new ArrayList <>();
         Listapedidos = new ArrayList <>();
          initComponents();
          cargarr();
        this.setLocationRelativeTo(null);
        this.crepasrealizadas = 0;
        this.totalrecaudado = 0;
        this.lista = "";
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public Double excelNumeric(int a, int b){
        try{
        FileInputStream File = new FileInputStream("C:\\Users\\Jorge Loredo\\Documents\\NetBeansProjects\\PortiAppp\\src\\portiappp\\Costos PortiCrepas.xlsx");
	XSSFWorkbook  hoja = new XSSFWorkbook(File);
        if (hoja.getSheetAt(0).getRow(a).getCell(b).getCellType() == XSSFCell.CELL_TYPE_STRING)
return Double.parseDouble(hoja.getSheetAt(0).getRow(a).getCell(b).getStringCellValue());

else if(hoja.getSheetAt(0).getRow(a).getCell(b).getCellType()== XSSFCell.CELL_TYPE_NUMERIC)
{
return hoja.getSheetAt(0).getRow(a).getCell(b).getNumericCellValue();
}
else if(hoja.getSheetAt(0).getRow(a).getCell(b).getCellType() == XSSFCell.CELL_TYPE_FORMULA){
    return hoja.getSheetAt(0).getRow(a).getCell(b).getNumericCellValue();
}
        hoja.close();
	File.close();
    }catch(Exception e){
        System.out.println("chale");
    } return -1.00;
    }
    public void verDatos(){
        String Mat[][] = new String [Listapedidos.size()][5];
        Crepa aux;
        for (int i = 0; i<Listapedidos.size(); i++){
            aux = Listapedidos.get(i);
            Mat[i][0] = aux.getNombre();
            Mat[i][1] = aux.getFondo();
            Mat[i][2] = aux.getElemento1();
            Mat[i][3] = aux.getElemento2();
            Mat[i][4] = aux.getEnv();
                    }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            Mat,
            new String [] {
                "Nombre", "Fondo", "Elemento 1", "Elemento2", "Envoltura"
            }
        ));
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("INGREDIENTE #2");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("INGREDIENTE #1");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("¿TIENE ENVOLTURA?");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jComboBox2.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Plátano", "Fresa", "Lechera" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 180, 30));

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nutella", "Cajeta", "Mermelada de fresa" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 180, 30));

        jComboBox3.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Plátano", "Fresa", "Lechera" }));
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 180, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("FONDO");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 390, 40));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NOMBRE:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ARMA TU CREPA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Terminar ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 10, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("SI = NO SE DA EMPAQUE");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        jComboBox4.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 180, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/portiappp/dd.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("COMPRAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 160, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/portiappp/red-wallpaper-background.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton4.setBackground(new java.awt.Color(255, 0, 0));
        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Crepa Hecha");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 410, 260, 30));

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Cancelar Crepa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 410, 240, 30));

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Fondo", "Ingrediente 1", "Ingrediente 2", "Envoltura"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, 540, 320));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/portiappp/red-wallpaper-background.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void cargarr(){
        File ruta = new File("listacrepas.txt");
        try{
            
            FileReader File = new FileReader(ruta);
            BufferedReader bu = new BufferedReader(File);
            
            
            String linea = null;
            while((linea = bu.readLine())!=null){
                StringTokenizer Token = new StringTokenizer(linea, ",");
                p = new Crepa();
                p.setNombre(Token.nextToken());
                p.setFondo(Token.nextToken());
                p.setElemento1(Token.nextToken());
                p.setElemento2(Token.nextToken());
                p.setEnv(Token.nextToken());
                listalocal.add(p);
            }
            bu.close();
        }catch(Exception ex){
            System.out.println("error");
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       gastos();
             File ruta = new File("listacrepas.txt");
            PrintWriter Escribe;
      if(!ruta.exists()){
            try{
                ruta.createNewFile();
            }catch(IOException e){
            }
        }
      try{
            
            FileReader fi = new FileReader(ruta);
            BufferedReader bu = new BufferedReader(fi);
            Crepa aux;
            for(int i= 0; i<Listapedidos.size(); i++){
                listalocal.add(Listapedidos.get(i));}
            bu.close();
     }catch(Exception ex){
            System.out.println("error");}
        try{
            Crepa aux;
            Escribe = new PrintWriter(ruta, "utf-8");
            for(int i= 0; i<listalocal.size(); i++){
                aux =listalocal.get(i);
                aux.guardar(Escribe);}
                Escribe.close();
            }catch(Exception e){     
        }

                
        this.Lista = "El dinero total recaudado de esta jornada es de: $" + this.totalrecaudado;
        this.Lista = this.Lista + ("\n" + "Los costos totales fueron de: $" + this.gastos);
        this.Lista = this.Lista + ("\n" + "Por lo tanto las ganancias totales fueron de: $" + (this.totalrecaudado-this.gastos));
        JOptionPane.showMessageDialog(null,Lista);
        
                PortiApp1 a = new PortiApp1();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
             this.crepasrealizadas++;
        
        int b = jComboBox1.getSelectedIndex();
     if(b==0){
         Fondo = "nutella";
         this.nutellas++;
     }
     if(b==1){
         Fondo = "cajeta";
         this.cajetas++;
     }
     if(b==2){
         Fondo = "mermelada de fresa";
         this.merme++;
     }
     
     int c = jComboBox2.getSelectedIndex();
     if(c==0){
         Elemento1 = "plátano";
         this.platanos++;
     }
     if(c==1){
         Elemento1 = "fresa";
         this.fresas++;
     }
     if(c==2){
         Elemento1 = "lechera";
         this.lecheras++;
     }
     
     int d = jComboBox3.getSelectedIndex();
     if(d==0){
         Elemento2 = "plátano";
         this.platanos++;
     }
     if(d==1){
         Elemento2 = "fresa";
         this.fresas++;
     }
     else if(d==2){
         Elemento2 = "lechera";
         this.lecheras++;
     }
     
     int e = jComboBox4.getSelectedIndex();
if(e==0){
    this.Envoltura = 20;
    envoltura = "SI";
}
else if(e ==1){
    this.Envoltura = 25;
    
envoltura = "NO";
this.Envolturas++;
}
else{
    this.Envoltura=20;
    envoltura = "SI";
}
     
       if(Fondo == null){
                    Fondo = "nutella";
       this.nutellas++;}
        if(Elemento1 == null){
            Elemento1 ="plátano";
        this.platanos++;}
        if(Elemento2 == null){
            Elemento2 = "plátano";
            this.platanos++;
        }
        
        
        nombre=jTextField1.getText();
        Listapedidos.add(new Crepa(nombre,Fondo,Elemento1,Elemento2,envoltura));
        verDatos();
        this.totalrecaudado = this.totalrecaudado + this.Envoltura;
        jTextField1.setText("");
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         int c;
        try{
            c = jTable1.getSelectedRow();
           listalocal.add(Listapedidos.get(c));
            Listapedidos.remove(c);
            
        }catch( Exception e){
            JOptionPane.showMessageDialog(null, "Favor de escoger una crepa");
        }
        verDatos();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int c;
        Crepa aux;

        try{
            c = jTable1.getSelectedRow();
            aux = Listapedidos.get(c);
            System.out.println(aux.getFondo());
            this.gastos=this.gastos - excelNumeric(7,7);
            if("nutella".equals(aux.getFondo()) ){
                this.gastos=this.gastos-excelNumeric(13,6);}//costo de nutella por unidad
            if("cajeta".equals(aux.getFondo())){
                this.gastos=this.gastos-excelNumeric(17,6);}//costo de cajeta por unidad
            if("mermelada de fresa".equals(aux.getFondo())){
                this.gastos=this.gastos-excelNumeric(14,6);}//costo de mermelada por unidad
            if("plátano".equals(aux.getElemento1())){
                this.gastos=this.gastos - excelNumeric(15,6);}//costo de platano por unidad
            if("fresa".equals(aux.getElemento1())){
                this.gastos = this.gastos - excelNumeric(16,6);}//costo de fresa por unidad
            if("lechera".equals(aux.getElemento1())){
                this.gastos = this.gastos - excelNumeric(12,6);} //costo de lechera por unidad
            if("plátano".equals(aux.getElemento2())){
                this.gastos=this.gastos - excelNumeric(15,6);}//costo de platano por unidad
            if("fresa".equals(aux.getElemento2())){
                this.gastos = this.gastos - excelNumeric(16,6);}//costo de fresa por unidad
            if("lechera".equals(aux.getElemento2())){
                this.gastos = this.gastos - excelNumeric(12,6);} //costo de lechera por unidad
            if("NO".equals(aux.getEnv())){
                this.gastos=this.gastos - excelNumeric(18,7);
                this.totalrecaudado = this.totalrecaudado - 25;}//costo de EMPAQUE por unidad
            if("SI".equals(aux.getEnv()))
            this.totalrecaudado = this.totalrecaudado - 20; //ingreso de venta sin empqeu

            Listapedidos.remove(c);

        }catch( Exception e){
            JOptionPane.showMessageDialog(null, "Favor de escoger una crepa");
        }
        verDatos();

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
public void gastos() {
        
      this.costomasa = this.crepasrealizadas*excelNumeric(7,7); //Segun el excel 2.307 es el costo de la masa de cada crepa
                this.gastos =this.gastos + this.nutellas * excelNumeric(13,6);    //3.33 es el precio promedio de añadirle nutella a la crepa
                this.gastos =this.gastos + this.cajetas * excelNumeric(17,6);    //3.16 es el precio promedio de añadirle cajeta a la crepa
                this.gastos =this.gastos + this.merme * excelNumeric(14,6);   //2.125 es el precio promedio de añadirle mermelada de fresa a la crepa
                this.gastos =this.gastos + this.platanos * excelNumeric(15,6);    //1.79 es el precio promedio de añadirle plátano a la crepa
                this.gastos =this.gastos + this.fresas * excelNumeric(16,6);   //3.375 es el precio promedio de añadirle fresa a la crepa
                this.gastos =this.gastos + this.lecheras * excelNumeric(12,6);   //1.375 es el precio promedio de añadirle lechera a la crepa
                this.gastos = this.gastos + this.Envolturas * excelNumeric(18,7);       //3.8 es el precio promedio de añadirle envoltura a la crepa
      this.gastos = this.gastos + this.costomasa; 
      this.gastos = (this.gastos);
}


}
